export interface ScreenDefinition {
  title: string;
  label: string;
  description: string;
  details: string[];
}

export const SCREEN_DEFINITIONS: Record<string, ScreenDefinition> = {
  achievements: {
    title: 'Achievements',
    label: 'MILESTONES',
    description: 'Review major AI progress markers and celebrate every companion milestone.',
    details: ['Streak tracking', 'Memory mastery', 'Voice interaction growth'],
  },
  advanced_memory_management: {
    title: 'Advanced Memory Management',
    label: 'INTELLIGENCE',
    description: 'Configure how Aura saves, recalls, and cleanses your conversation history.',
    details: ['Memory retention policy', 'Trusted topics', 'Secure recall controls'],
  },
  age_verification: {
    title: 'Age Verification',
    label: 'SECURITY',
    description: 'Confirm your age to access safe companion features and content restrictions.',
    details: ['Prove age securely', 'Verified experience', 'Designed for maturity'],
  },
  ai_disclosure_screen: {
    title: 'AI Disclosure',
    label: 'TRANSPARENCY',
    description: 'Learn how Aura works, what data is used, and how trust is maintained.',
    details: ['How responses are generated', 'Data use policy', 'Safety layers'],
  },
  chat_experience: {
    title: 'Chat Experience',
    label: 'INTERACTION',
    description: 'Enjoy a premium conversation interface with expressive AI feedback and glassmorphic depth.',
    details: ['Real-time voice mode', 'Smart suggestions', 'Memory-aware responses'],
  },
  chat_history: {
    title: 'Chat History',
    label: 'ARCHIVE',
    description: 'Browse past conversations and quickly jump back into meaningful moments.',
    details: ['Search by topic', 'Timeline view', 'Pinned memories'],
  },
  companion_avatar_creator: {
    title: 'Companion Avatar Creator',
    label: 'PERSONALIZE',
    description: 'Design your AI companion’s avatar with mood, glow, and persona styling.',
    details: ['Orb generator', 'Glow presets', 'Mood-based themes'],
  },
  companion_details: {
    title: 'Companion Details',
    label: 'PROFILE',
    description: 'Edit the companion’s backstory, voice, and behavior attributes in a refined panel.',
    details: ['Name & origin', 'Personality traits', 'Preferred tone'],
  },
  companion_gallery: {
    title: 'Companion Gallery',
    label: 'SHOWCASE',
    description: 'Explore curated AI companion designs and discover new energy personas.',
    details: ['Featured companions', 'Mood collections', 'Save favorites'],
  },
  create_companion: {
    title: 'Create Companion',
    label: 'NEW EXPERIENCE',
    description: 'Build your ideal AI partner from character, voice, and memory style options.',
    details: ['Persona selection', 'Voice type', 'Memory depth'],
  },
  daily_check_in: {
    title: 'Daily Check-In',
    label: 'REFLECTION',
    description: 'Log your mood and receive a gentle AI prompt tailored to your day.',
    details: ['Mood input', 'Wellness guidance', 'Daily insights'],
  },
  delete_account: {
    title: 'Delete Account',
    label: 'RESET',
    description: 'Permanently remove your account and companion data with clear transparency.',
    details: ['Data removal', 'Confirmation flow', 'Help resources'],
  },
  discovery: {
    title: 'Discovery',
    label: 'EXPLORE',
    description: 'Find new companion features, AI utilities, and curated inspiration.',
    details: ['Trend cards', 'New experiences', 'Suggested journeys'],
  },
  edit_companion: {
    title: 'Edit Companion',
    label: 'CUSTOMIZE',
    description: 'Fine-tune the AI companion’s voice, tone, and memory preferences anytime.',
    details: ['Adjust demeanor', 'Change style', 'Review traits'],
  },
  forgot_password: {
    title: 'Forgot Password',
    label: 'RECOVERY',
    description: 'Recover access to your account with a secure password reset flow.',
    details: ['Send verification', 'Secure reset', 'Help if stuck'],
  },
  help_support: {
    title: 'Help & Support',
    label: 'ASSIST',
    description: 'Access help articles, safety guides, and direct support resources.',
    details: ['FAQs', 'Contact support', 'Report issues'],
  },
  home_dashboard: {
    title: 'Home Dashboard',
    label: 'OVERVIEW',
    description: 'Your central companion hub with status, shortcuts, and experience highlights.',
    details: ['Daily status', 'Active companion', 'Recent memories'],
  },
  invite_friends: {
    title: 'Invite Friends',
    label: 'SHARE',
    description: 'Bring friends into Aura and earn premium rewards for every invited connection.',
    details: ['Invite links', 'Reward tracking', 'Share easily'],
  },
  login_screen: {
    title: 'Login',
    label: 'ACCESS',
    description: 'Sign in to your companion account with secure biometric and password options.',
    details: ['Email login', 'Phone sign-in', 'Biometric unlock'],
  },
  memory_search: {
    title: 'Memory Search',
    label: 'FIND',
    description: 'Search your companion’s remembered moments with natural filters and tags.',
    details: ['Keyword search', 'Category filters', 'Recent items'],
  },
  memory_timeline: {
    title: 'Memory Timeline',
    label: 'TIMELINE',
    description: 'Scroll your relationship history with Aura through an elegant timeline view.',
    details: ['Moment snapshots', 'Date anchors', 'Memory highlights'],
  },
  mood_tracker: {
    title: 'Mood Tracker',
    label: 'EMOTION',
    description: 'Track your emotional state and let Aura respond with empathetic support.',
    details: ['Mood history', 'Daily patterns', 'Personal notes'],
  },
  notification_center: {
    title: 'Notification Center',
    label: 'ALERTS',
    description: 'Manage your companion notices, reminders, and important system updates.',
    details: ['Message alerts', 'Safety notices', 'Product updates'],
  },
  onboarding_1: {
    title: 'Onboarding 1',
    label: 'START',
    description: 'Welcome to Aura with an immersive introduction to the companion experience.',
    details: ['Hello setup', 'Overview of features', 'First steps'],
  },
  onboarding_2: {
    title: 'Onboarding 2',
    label: 'DISCOVERY',
    description: 'Learn how Aura stores memory and supports natural voice-first interaction.',
    details: ['Memory benefits', 'Voice mode', 'Privacy assurances'],
  },
  onboarding_3: {
    title: 'Onboarding 3',
    label: 'PERSONALIZE',
    description: 'Tailor your companion with mood, persona, and energy preferences.',
    details: ['Choose tone', 'Set goals', 'Refine style'],
  },
  onboarding_4: {
    title: 'Onboarding 4',
    label: 'SECURE',
    description: 'Set up your safety preferences and AI boundaries for a trusted companion relationship.',
    details: ['Break reminders', 'Consent settings', 'Safety tips'],
  },
  onboarding_5: {
    title: 'Onboarding 5',
    label: 'READY',
    description: 'Complete setup and launch your Aura companion into your daily routine.',
    details: ['Review journey', 'Enable reminders', 'Get started'],
  },
  payment_checkout: {
    title: 'Payment Checkout',
    label: 'PURCHASE',
    description: 'Complete your premium plan purchase in a secure, polished checkout experience.',
    details: ['Payment methods', 'Order summary', 'Secure confirmation'],
  },
  premium_plans: {
    title: 'Premium Plans',
    label: 'UPGRADE',
    description: 'Compare premium tiers and choose the best Aura experience for your needs.',
    details: ['Plan benefits', 'Price details', 'Annual savings'],
  },
  premium_showcase: {
    title: 'Premium Showcase',
    label: 'FEATURES',
    description: 'Browse premium companion capabilities, exclusive modes, and luxury upgrades.',
    details: ['Enhanced memory', 'Voice enhancements', 'Priority access'],
  },
  privacy_center: {
    title: 'Privacy Center',
    label: 'PRIVACY',
    description: 'Control your data, personalize privacy settings, and review Aura’s safeguards.',
    details: ['Data controls', 'Policy overview', 'Security options'],
  },
  referral_program: {
    title: 'Referral Program',
    label: 'REWARD',
    description: 'Earn rewards for inviting others and growing the Aura companion community.',
    details: ['Invite rewards', 'Progress tracking', 'Share options'],
  },
  register_screen: {
    title: 'Register',
    label: 'JOIN',
    description: 'Create your Aura account to begin building a personal AI companion experience.',
    details: ['Sign-up details', 'Secure verification', 'Welcome perks'],
  },
  relationship_timeline: {
    title: 'Relationship Timeline',
    label: 'JOURNEY',
    description: 'Visualize your evolving bond with Aura through curated memory milestones.',
    details: ['Timeline view', 'Emotion markers', 'Milestone highlights'],
  },
  safety_center: {
    title: 'Safety Center',
    label: 'SUPPORT',
    description: 'Access safety tools, coping prompts, and emergency resources at a glance.',
    details: ['Crisis support', 'Boundaries', 'Trusted contacts'],
  },
  settings_screen: {
    title: 'Settings',
    label: 'CONTROL',
    description: 'Adjust your Aura experience, notifications, and personalization settings.',
    details: ['App preferences', 'Voice options', 'Account controls'],
  },
  shader: {
    title: 'Shader',
    label: 'VISUALS',
    description: 'A visual effects canvas that brings Aura’s ambiance to life with subtle texture and motion.',
    details: ['Ambient glow', 'Depth effects', 'Motion layers'],
  },
  splash_screen: {
    title: 'Splash Screen',
    label: 'INTRO',
    description: 'A cinematic launch experience with glowing orbs and fluid motion.',
    details: ['Branded entrance', 'Loading animation', 'Immersive mood'],
  },
  user_profile: {
    title: 'User Profile',
    label: 'ME',
    description: 'View and edit your personal profile, preferences, and companion settings.',
    details: ['Profile info', 'Account options', 'Interaction summary'],
  },
  user_statistics: {
    title: 'User Statistics',
    label: 'STATS',
    description: 'Analyze your Aura engagement with high-level usage and mood insights.',
    details: ['Activity metrics', 'Mood breakdown', 'Interaction frequency'],
  },
  voice_call: {
    title: 'Voice Call',
    label: 'LIVE',
    description: 'Launch a voice session with Aura using a premium sound interface and companion feedback.',
    details: ['Mic controls', 'Live waveform', 'Session status'],
  },
  voice_companion_setup: {
    title: 'Voice Companion Setup',
    label: 'SETUP',
    description: 'Choose your companion’s voice, pacing, and speech style for natural conversation.',
    details: ['Voice presets', 'Tone balance', 'Speaking style'],
  },
  voice_settings: {
    title: 'Voice Settings',
    label: 'AUDIO',
    description: 'Fine-tune speech volume, voice pitch, and playback preferences for Aura interactions.',
    details: ['Volume control', 'Speed sliders', 'Voice personalization'],
  },
  welcome_screen: {
    title: 'Welcome Screen',
    label: 'HELLO',
    description: 'Step into Aura with a lavish welcome screen shaped by luminous glass and rich motion.',
    details: ['Hero introduction', 'Feature highlights', 'Start journey'],
  },
};
